image:
  name: docker.imanage.com/ravn-java11-maven-base:latest
  username: $ARTIFACTORY_USERNAME
  password: $ARTIFACTORY_PASSPHRASE

definitions:
  steps:
    - step: &maven-verify
        name: Maven Verify
        caches:
          - maven
        script:
          - bash create-settings.sh
          # Skip tests as there are lots of test failures in Apache Tika project
          - mvn -B -s settings.xml -DskipTests clean verify

    - step: &upload-to-artifactory
        name: Upload to Artifactory
        caches:
          - maven
        script:
          - bash create-settings.sh
          # Skip tests as there are lots of test failures in Apache Tika project
          - mvn -B -s settings.xml -DskipTests clean deploy

pipelines:
  branches:
    master:
      - step: *upload-to-artifactory
  pull-requests:
    '**':
      - step: *maven-verify
