#!/bin/bash

DIR="$(dirname "${BASH_SOURCE[0]}")"
TEMPLATE_FILE=$DIR/settings.template.xml
DEST_FILE_NAME=settings.xml
DESTINATION_FILE=$DIR/$DEST_FILE_NAME
GITIGNORE=$DIR/.gitignore

echo "Checking for presence of ARTIFACTORY_USERNAME environment variable...."
if [[ $ARTIFACTORY_USERNAME ]];
then
  echo "Success - Found ARTIFACTORY_USERNAME in environment variables...";
else
  >&2 echo "Failure - ARTIFACTORY_USERNAME environment variable not set.  Please set this environment variable and try again."
  exit 1
fi;

echo "Checking for presence of ARTIFACTORY_PASSPHRASE environment variable...."
if [[ $ARTIFACTORY_PASSPHRASE ]];
then
  echo "Success - Found ARTIFACTORY_PASSPHRASE in environment variables...";
else
  >&2 echo "Failure - ARTIFACTORY_PASSPHRASE environment variable not set.  Please set this environment variable and try again."
  exit 2
fi;

echo "Environment Variables Set, Creating $DESTINATION_FILE file..."

if [ -f $TEMPLATE_FILE ]; then
   if cat $TEMPLATE_FILE | sed  "s/%ARTIFACTORY_USERNAME%/$ARTIFACTORY_USERNAME/g"  | sed "s/%ARTIFACTORY_PASSPHRASE%/$ARTIFACTORY_PASSPHRASE/g" | sed "s/generation text/ATTENTION: This file was generated by the create-settings.sh script.  Do not commit it to version control as it contains credentials!/" > $DESTINATION_FILE; then

      if grep -q "^$DEST_FILE_NAME$" $GITIGNORE; then
         echo "Success - $DEST_FILE_NAME found in $GITIGNORE file.  This will prevent git from saving the credentials in version control."
         else
         echo "Warning - $DEST_FILE_NAME not found in $GITIGNORE file.  Add $DEST_FILE_NAME to $GITIGNORE to ensure you don't accidentally commit your credentials!"
      fi

      echo "Success - $DESTINATION_FILE file successfully created.  Make sure you do not commit this file to source control."
      exit 0;
   else
      >&2 echo "Failure - There was an error creating the $DESTINATION_FILE";
      exit 3;

   fi;
else
   >&2 echo "Failure - $TEMPLATE_FILE does not exist";
   exit 4;
fi;